services:
  - type: web
    name: sushant-elibrary
    runtime: docker
    plan: free
    region: oregon
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
